---
logs_dir_zuul: "/home/zuul/ci-framework-data/logs"
artifacts_dir_zuul: "/home/zuul/ci-framework-data/artifacts"

ck_synth_script: "{{ role_path }}/files/gen_synth_loki_data.py"
ck_data_template: "{{ role_path }}/template/loki_data_templ.j2"
# Path to the scenario configuration file.
ck_data_config: "{{ role_path }}/files/test_dyn_basic.yml"
# Local path for generated synthetic data.
ck_output_file_local: "{{ artifacts_dir_zuul }}/loki_synth_data.json"
ck_output_file_remote: "{{ logs_dir_zuul }}/gen_loki_synth_data.log"
