---
# Scenario and script paths (using role_path)
cloudkitty_scenario_dir: "{{ role_path }}/files"
cloudkitty_synth_script: "{{ role_path }}/files/gen_synth_loki_data.py"
cloudkitty_data_template: "{{ role_path }}/templates/loki_data_templ.j2"
cloudkitty_summary_script: "{{ role_path }}/files/gen_db_summary.py"

# File naming conventions (internal standardization)
cloudkitty_synth_data_suffix: "-data_synth.json"
cloudkitty_loki_data_suffix: "-data_loki.json"
cloudkitty_synth_totals_metrics_suffix: "-metrics_summary_synth.yml"
cloudkitty_loki_totals_metrics_suffix: "-metrics_summary_loki.yml"
cloudkitty_loki_totals_suffix: "-rate_totals.yml"

cloudkitty_data_file: >-
  {{ artifacts_dir_zuul }}/{{ scenario_name }}{{ cloudkitty_synth_data_suffix }}
cloudkitty_synth_totals_file: >-
  {{ artifacts_dir_zuul }}/{{ scenario_name }}{{ cloudkitty_synth_totals_metrics_suffix }}
cloudkitty_test_file: >-
  {{ cloudkitty_scenario_dir }}/{{ scenario_name }}.yml

# initialize var
previous_end_time: ""
