---
# Scenario and script paths (using role_path)
cloudkitty_scenario_dir: "{{ role_path }}/files"
cloudkitty_synth_script: "{{ role_path }}/files/gen_synth_loki_data.py"
cloudkitty_data_template: "{{ role_path }}/templates/loki_data_templ.j2"
cloudkitty_summary_script: "{{ role_path }}/files/gen_db_summary.py"
