---
openstack_cmd: "openstack"

common_crd_test_id: "TEST"
common_cr_test_id: "TEST"
common_cr_ready_test_id: "TEST"
common_container_test_id: "TEST"
common_endpoint_test_id: "TEST"
common_file_test_id: "TEST"
common_manifest_test_id: "TEST"
common_pod_test_id: "TEST"
common_project_test_id: "TEST"
common_service_test_id: "TEST"
common_subscription_test_id: "TEST"
