- name: Verify ceilometer scrapeconfig exists
  ansible.builtin.include_role:
    name: common
  vars:
    common_cr_list:
      - kind: scrapeconfigs.monitoring.rhobs
        name: telemetry-ceilometer

- name: Verify ceilometer ipmi agent container is up
  ansible.builtin.include_tasks:
    file: check_compute_node_containers.yml
  vars:
    common_container_list:
      - ceilometer_agent_ipmi
  loop: "{{ groups['computes'] }}"
  loop_control:
    loop_var: compute_node

- name: Verify ceilometer controlplane pod is running
  ansible.builtin.include_role:
    name: common
  vars:
    common_pod_status_str: "Running"
    common_pod_nspace: openstack
    common_pod_list:
      - ceilometer-0

- name: Query the ceilometer ipmi fan metric
  when: verify_metrics_prereqs_ok | bool
  ansible.builtin.shell: |
    {{ openstack_cmd }} metric show ceilometer_hardware_ipmi_fan --disable-rbac
  register: ipmi_result
  delay: 30
  retries: 10
  changed_when: false
  ignore_errors: true
  until: ipmi_result.rc == 0 and "ceilometer_hardware_ipmi" in ipmi_result.stdout

- name: |
    TEST Use openstack observabilityclient to verify ceilometer ipmi metrics are stored in prometheus
  ansible.builtin.assert:
    that:
      - ipmi_result is not skipped
      - ipmi_result is not failed
    success_msg: "ceilometer_hardware_ipmi_fan is stored in prometheus"
    fail_msg: >-
      {{ (ipmi_result is not skipped)
         | ternary('ceilometer_hardware_ipmi_fan was not found in prometheus',
                   verify_metrics_blocked_msg) }}
