- name: Verify openstack network exporter scrapeconfigs exist
  ansible.builtin.include_role:
    name: common
  vars:
    common_cr_list:
      - kind: scrapeconfigs.monitoring.rhobs
        name: telemetry-openstack-network-exporter
      - kind: scrapeconfigs.monitoring.rhobs
        name: telemetry-openstack-network-exporter-tls

- name: Verify openstack network exporter container is up
  ansible.builtin.include_tasks:
    file: check_compute_node_containers.yml
  vars:
    common_container_list:
      - openstack_network_exporter
  loop: "{{ groups['computes'] }}"
  loop_control:
    loop_var: compute_node

- name: Query the openstack network exporter build info metric
  when: verify_metrics_prereqs_ok | bool
  ansible.builtin.shell: |
    {{ openstack_cmd }} metric show --disable-rbac ovs_build_info
  register: one_result
  delay: 30
  retries: 10
  changed_when: false
  ignore_errors: true
  until: one_result.rc == 0 and "ovs_build_info" in one_result.stdout

- name: |
    TEST Use openstack observabilityclient to verify Openstack Network Exporter metrics are stored in prometheus
  ansible.builtin.assert:
    that:
      - one_result is not skipped
      - one_result is not failed
    success_msg: "ovs_build_info is stored in prometheus"
    fail_msg: >-
      {{ (one_result is not skipped)
         | ternary('ovs_build_info was not found in prometheus',
                   verify_metrics_blocked_msg) }}
