---
- name: "Verify journal entries"
  when: journal_list is defined
  ansible.builtin.include_tasks: "journal_tests.yml"
  loop: "{{ journal_list }}"

- name: "Verify rsyslog template configuration"
  ansible.builtin.include_tasks: "rsyslog_template_tests.yml"
