---
### cleans up after each test scenario
- name: "Cleanup certificate directories"
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ cert_dir | default('') }}"
    - "{{ local_cert_dir | default('') }}"
  when: item | length > 0

- name: "Cleanup remote certificate directory in OpenStack Client pod"
  ansible.builtin.command:
    cmd: "oc exec -n {{ cloudkitty_namespace }} {{ openstackpod }} -- rm -rf {{ remote_cert_dir }}"
  changed_when: false
  failed_when: false
