---
# Flush Loki Ingester Memory to Storage

- name: "Flush execution inside OpenStack Client Pod"
  block:
    # create dir
    - name: "Create directory inside OpenStack Client pod"
      ansible.builtin.command:
        cmd: "oc exec -n {{ cloudkitty_namespace }} {{ openstackpod }} -- mkdir -p {{ remote_cert_dir }}"
      changed_when: false

    # copy all certs
    - name: "Copy certificates to OpenStack Client pod"
      ansible.builtin.command:
        cmd: "oc cp {{ local_cert_dir }}/. {{ cloudkitty_namespace }}/{{ openstackpod }}:{{ remote_cert_dir }}/"
      changed_when: true

    # flush loki
    - name: "Trigger Loki ingester flush"
      ansible.builtin.command:
        cmd: >
          oc exec -n {{ cloudkitty_namespace }} {{ openstackpod }} --
          curl -v -X POST {{ ingester_flush_url }}
          --cert {{ remote_cert_dir }}/tls.crt
          --key {{ remote_cert_dir }}/tls.key
          --cacert {{ remote_cert_dir }}/service-ca.crt
      register: flush_response
      changed_when: true
      failed_when: flush_response.rc != 0

    # Status
    - name: "Verify flush status"
      ansible.builtin.assert:
        that:
          - "'204' in flush_response.stderr or '200' in flush_response.stderr"
        fail_msg: "Flush failed"
        success_msg: "Ingester Memory Flushed successfully"

  rescue:
    - name: "Debug failure output"
      ansible.builtin.debug:
        msg: "Failure Data: {{ flush_response | default('No response captured') | to_json }}"
