---
# Flush Loki Ingester Memory to Storage

- name: "Flush execution inside OpenStack Client Pod"
  block:
    # create dir
    - name: "Create directory inside OpenStack Client pod"
      ansible.builtin.command:
        cmd: "oc exec -n {{ cloudkitty_namespace }} {{ openstackpod }} -- mkdir -p {{ remote_cert_dir }}"
      changed_when: false

    # copy all certs
    - name: "Copy certificates to OpenStack Client pod"
      ansible.builtin.command:
        cmd: "oc cp {{ local_cert_dir }}/. {{ cloudkitty_namespace }}/{{ openstackpod }}:{{ remote_cert_dir }}/"
      changed_when: true

    # flush loki
<<<<<<< alexy_ck_job_4
    - name: "Trigger Loki ingester flush"
      ansible.builtin.command:
        cmd: >
          oc exec -n {{ cloudkitty_namespace }} {{ openstackpod }} --
          curl -v -X POST {{ ingester_flush_url }}
=======
    - name: "TEST Trigger Loki ingester flush"
      ansible.builtin.command:
        cmd: >
          oc exec -n {{ cloudkitty_namespace }} {{ openstackpod }} --
          curl -s -w '%{http_code}' -X POST {{ ingester_flush_url }}
>>>>>>> master
          --cert {{ remote_cert_dir }}/tls.crt
          --key {{ remote_cert_dir }}/tls.key
          --cacert {{ remote_cert_dir }}/service-ca.crt
      register: flush_response
      changed_when: true
<<<<<<< alexy_ck_job_4
      failed_when: flush_response.rc != 0
=======
      any_errors_fatal: true
>>>>>>> master

    # Status
    - name: "Verify flush status"
      ansible.builtin.assert:
        that:
<<<<<<< alexy_ck_job_4
          - "'204' in flush_response.stderr or '200' in flush_response.stderr"
        fail_msg: "Flush failed"
=======
          - "flush_response.stdout in ['200', '204']"
        fail_msg: "Flush failed with status: {{ flush_response.stdout }}"
>>>>>>> master
        success_msg: "Ingester Memory Flushed successfully"

  rescue:
    - name: "Debug failure output"
      ansible.builtin.debug:
        msg: "Failure Data: {{ flush_response | default('No response captured') | to_json }}"
