---
- name: "Check for preexisting output file"
  ansible.builtin.stat:
    path: "{{ cloudkitty_data_file }}"
  register: file_preexists

- name: "Initialize previous_end_time if not set"
  ansible.builtin.set_fact:
    previous_end_time: ""
  when: previous_end_time is not defined

- name: "TEST Generate Synthetic Data for {{ scenario_name }}"
  ansible.builtin.command:
    cmd: >
      python3 "{{ cloudkitty_synth_script }}"
      --tmpl "{{ cloudkitty_data_template }}"
      -t "{{ cloudkitty_test_file }}"
      -o "{{ cloudkitty_data_file }}"
      --debug "{{ cloudkitty_debug }}"
      --end_time "{{ previous_end_time }}"
  register: cloudkitty_data_file_output
  when: not file_preexists.stat.exists | bool
  changed_when: cloudkitty_data_file_output.rc == 0
  any_errors_fatal: true

- name: "Set end_time parameter value for {{ scenario_name }}"
  ansible.builtin.set_fact:
    previous_end_time: >-
      {{ cloudkitty_data_file_output.stdout | regex_replace('^oldest_start_time=', '') }}
  when: >-
    cloudkitty_data_file_output.stdout is defined and
    cloudkitty_data_file_output.stdout | length > 0

- name: "TEST Generate chargeback rating from synthetic data file {{ scenario_name }}"
  ansible.builtin.command:
    cmd: >
      python3 "{{ cloudkitty_summary_script }}"
      -j "{{ cloudkitty_data_file }}"
      -o "{{ cloudkitty_synth_totals_file }}"
      --debug "{{ cloudkitty_debug }}"
      --debug_dir "{{ cloudkitty_debug_dir }}"
  register: cloudkitty_synth_totals_file_output
  when: not file_preexists.stat.exists | bool
  changed_when: cloudkitty_synth_totals_file_output.rc == 0
  any_errors_fatal: true

# Load synthetic metrics summary for validation
- name: "Load synthetic metrics summary for {{ scenario_name }}"
  ansible.builtin.include_vars:
    file: "{{ cloudkitty_synth_totals_file }}"
    name: synth_data_rates
  when: cloudkitty_synth_totals_file_output is defined
