---
- name: "Validate Chargeback Feature deployed correctly"
  ansible.builtin.include_tasks: "chargeback_tests.yml"

- name: "Setup Loki Environment"
  ansible.builtin.include_tasks: "setup_loki_env.yml"

# Scenario name is file name without extension
- name: "Generate clean list of scenario names"
  ansible.builtin.set_fact:
    scenarios_to_run: "{{ cloudkitty_test_scenarios | map('regex_replace', '\\.yml$', '') | list }}"

- name: "Run scenarios through workflow"
# Test scenarios run in time sequence using "cloudkitty_test_scenarios" list order
  block:
    - name: "Process and Loop if files exist"
      ansible.builtin.include_tasks: "run_test_scenarios.yml"
      loop: "{{ scenarios_to_run | reverse | list }}"
      loop_control:
        loop_var: scenario_name
      when: scenarios_to_run | length > 0

    - name: "Get total rate from Loki: {{ scenario_name }}"
      ansible.builtin.include_tasks: "loki_total_rate.yml"     

  rescue:
    - name: "Log failure"
      ansible.builtin.fail:
        msg: "Running test scenarios loop failed. Please check logs"

  always:
    - name: "Cleanup after job run"
      ansible.builtin.include_tasks: "cleanup_ck.yml"
