---
- name: "Generate Synthetic Data for each file: {{ scenario_name }}"
  ansible.builtin.include_tasks: "gen_synth_loki_data.yml"

- name: "Load data to Loki: {{ scenario_name }}"
  ansible.builtin.include_tasks: "load_loki_data.yml"

- name: "Diff Loki DB upload vs download {{ scenario_name }}"
  ansible.builtin.include_tasks: "loki_diff_db_upload-vs-download.yml"

- name: "Get total rate from Loki: {{ scenario_name }}"
  ansible.builtin.include_tasks: "loki_rate.yml"    
