---
# Following procedure on https://infrawatch.github.io/documentation/#metrics-retention-time-period_assembly-advanced-features
# Assuming we've already logged in.
# Assuming we're in the right project already...

- name: "Test updating the metrics retention time"
  ansible.builtin.include_tasks:
    file: test_update_metrics_retention.yml
