---
- name: Get stats for file - "{{ file.name }}"
  ansible.builtin.stat:
    path: "{{ ifile.name }}"
  register: fstats
  failed_when: 
    - fstats.stat.pw_name != "root"
    - fstats.stat.size | int < 300
    - not fstats.stat.exists
    - not fstats.stat.isreg
