---
galaxy_info:
  author: Red Hat CloudOps team
  description: Verify OpenStack API audit events are emitted and stored in Loki
  company: Red Hat

  license: Apache-2.0

  min_ansible_version: "2.9"

  galaxy_tags: []

dependencies: []
