---
- name: "Verify logging journalctl identifiers"
  hosts: computes
  gather_facts: true
  ignore_errors: true
  environment:
    KUBECONFIG: "{{ cifmw_openshift_kubeconfig }}"
    PATH: "{{ cifmw_path }}"
  vars:
    #telemetry_logging_journal_test_id: "RHOSO-12681"
    telemetry_logging_journal_list:
      - { name: ceilometer_agent_compute, test_id: "RHOSO-12681" }
      - { name: nova_compute, test_id: "RHOSO-12681" }
  tasks:
    - name: "Run Telemetry Logging tests"
      ansible.builtin.include_role:
        name: telemetry_logging
