---
- name: Move callback_plugin result to log dir
  ansible.builtin.shell:
    cmd: |
      cp  ~/test_run_result.out {{ autoscaling_logs_dir }}/test_run_result.log
     # cp  ~/summary_results.log {{ autoscaling_logs_dir }}/summary_results.log

- name: Grep the number of failed tasks
  ansible.builtin.shell:
    cmd: |
      grep -c "failed" ~/test_run_result.out
  register: tasks_failed
  changed_when: false

- name: Determine success or failure based on the number of failed tasks
  ansible.builtin.assert:
    that:
      -  tasks_failed.stdout|int == 0
    fail_msg: "Tasks Failed: {{ tasks_failed.stdout }}. Check the logs ."
    success_msg: "Tasks Failed: {{ tasks_failed.stdout }}. All tasks succeeded."